In [2]:
import pandas as pd
df = pd.read_csv("grafana_sorted_2021.csv", header = 0, sep=",")
df

                  Time     Power       Date  day  month  year
0       18:25:54+05:00   8985.21  2/18/2021    2     18  2021
1       18:26:24+05:00   9044.73  2/18/2021    2     18  2021
2       18:26:54+05:00   9063.51  2/18/2021    2     18  2021
3       18:27:24+05:00   9078.22  2/18/2021    2     18  2021
4       18:27:54+05:00   9046.88  2/18/2021    2     18  2021
...                ...       ...        ...  ...    ...   ...
498518  14:16:42+05:00  10584.91  8/11/2021    8     11  2021
498519  14:17:12+05:00  10627.91  8/11/2021    8     11  2021
498520  14:17:42+05:00  10575.83  8/11/2021    8     11  2021
498521  14:18:12+05:00  10533.15  8/11/2021    8     11  2021
498522  14:18:42+05:00  10594.13  8/11/2021    8     11  2021

[498523 rows x 6 columns]

In [11]:
pd.Period('2021-02-18').days_in_month

28